### ISSUE TITLE
Flatpak version from Flathub won't allow sign-in to Todoist

### ISSUE THREAD

**Issue by rsdundon** [flathub/com.github.alainm23.planner#3]
On Manjaro, fully updated. When I try to login to Todoist to sync my tasks, the login screen accepts my username and password, but instead of logging me into Todoist the login screen is replaced by your Github page.

![image](https://user-images.githubusercontent.com/63672337/85954913-bcc74980-b92f-11ea-8bf0-194183aec7ed.png)

I've tried from Pamac and the cli, same result.

Thanks!

Bob

**Comment by alainm23** [comment]
Fixed [here](https://github.com/alainm23/planner/issues/424). Update to v2.4.4
